#!/usr/bin/env python3

import sys
from sys import argv
from math import sqrt

def open_read_file(file_name):
	with open(file_name, "r", encoding="utf-8") as file:
		lines = file.readlines()
	number_to_factor = []
	for line in lines:
		number_to_factor.append(int(line))
	return number_to_factor


if __name__ == "__main__":
	if len(sys.argv) != 2:
		print("Usage: {} <file>".format(sys.argv[0]))
		sys.exit(1)

	ls = (open_read_file(argv[1]))
	for i in ls:
		for k in range(1, i):
			if i == ((i // k) * k):
				print("{}={}*{}".format(i, (i // k), k))
				break
